[package]
name = "shuffle_sharding"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash = "0.8.11"
dashmap = "5.5.3"
md5 = "0.7.0"
rand = { version = "*", features = ["small_rng"] }
rand_chacha = "0.3"
wyhash = "0.5.0"
[profile.release]
debug = true
